### ISSUE TITLE
Hard crash on `TServer::Apply`

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#37]
- OS: Ubuntu 20.04.2 LTS
- Server Version: v2.1.3 (master branch)

Attached is the 130 MB (!) server log. The server was running west_coast_usa.

The error itself is 
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
```

The gdb backtrace of the crash is
```cpp
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7895859 in __GI_abort () at abort.c:79
#2  0x000055555577f43a in __gnu_cxx::__verbose_terminate_handler() [clone .cold] ()
#3  0x000055555589d94c in __cxxabiv1::__terminate(void (*)()) ()
#4  0x000055555589d9b7 in std::terminate() ()
#5  0x000055555589db19 in __cxa_throw ()
#6  0x0000555555780da0 in std::__throw_out_of_range_fmt(char const*, ...) [clone .cold] ()
#7  0x0000555555920d73 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const ()
#8  0x0000555555796668 in TServer::Apply (c=..., VID=0, pckt=...) at /root/BeamMP-Server/src/TServer.cpp:318
#9  0x000055555579361e in TServer::ParseVehicle (c=..., Pckt=..., Network=...) at /root/BeamMP-Server/src/TServer.cpp:245
#10 0x000055555578f625 in TServer::GlobalParser (Client=..., Packet=..., PPSMonitor=..., Network=...) at /root/BeamMP-Server/src/TServer.cpp:114
#11 0x000055555588c219 in TNetwork::TCPClient (this=0x7fffffffdcc0, c=...) at /root/BeamMP-Server/src/TNetwork.cpp:556
#12 0x00005555558870ec in TNetwork::Authentication (this=0x7fffffffdcc0, TCPSock=14) at /root/BeamMP-Server/src/TNetwork.cpp:341
#13 0x0000555555884210 in TNetwork::Identify (this=0x7fffffffdcc0, TCPSock=14) at /root/BeamMP-Server/src/TNetwork.cpp:218
#14 0x0000555555898d45 in std::__invoke_impl<void, void (TNetwork::*)(int), TNetwork*, int> (__f=@0x7fffe0002298: (void (TNetwork::*)(class TNetwork * const, int)) 0x55555588415e <TNetwork::Identify(int)>,__t=@0x7fffe0002290: 0x7fffffffdcc0) at /usr/include/c++/9/bits/invoke.h:73
#15 0x0000555555898a91 in std::__invoke<void (TNetwork::*)(int), TNetwork*, int> (__fn=@0x7fffe0002298: (void (TNetwork::*)(class TNetwork * const, int)) 0x55555588415e <TNetwork::Identify(int)>) at /usr/include/c++/9/bits/invoke.h:95
#16 0x000055555589887f in std::thread::_Invoker<std::tuple<void (TNetwork::*)(int), TNetwork*, int> >::_M_invoke<0ul, 1ul, 2ul> (this=0x7fffe0002288) at /usr/include/c++/9/thread:244 
#17 0x000055555589878e in std::thread::_Invoker<std::tuple<void (TNetwork::*)(int), TNetwork*, int> >::operator( (this=0x7fffe0002288) at /usr/include/c++/9/thread:251
#18 0x000055555589872c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (TNetwork::*)(int), TNetwork*, int> > >::_M_run (this=0x7fffe0002280) at /usr/include/c++/9/thread:195
#19 0x0000555555921104 in execute_native_thread_routine ()
#20 0x00007ffff7f7b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007ffff7992293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

The crash happens in `TServer.cpp:318` in a `std::string::substr`, that's this line:

```cpp
VD = VD.substr(VD.find('{'));
```

From what I can see, this happens right after the user "Bruh2556" creates 4 cars in a row, then deletes one, to which the server says
```
Bruh2556" Client.cpp:16 [DEBUG] tried to erase a vehicle that doesn't exist (not an error)
```

**Comment by lionkor** [comment]
It didn't let me attach the log (as i said, 130MB), but the relevant parts are explained.
